// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0_fnInAMNI_QxDtNLjJhv8UNoJcunczg',
    appId: '1:482543933000:web:169f8a18d1676e30c2aa7d',
    messagingSenderId: '482543933000',
    projectId: 'animagie-8f2fe',
    authDomain: 'animagie-8f2fe.firebaseapp.com',
    storageBucket: 'animagie-8f2fe.appspot.com',
    measurementId: 'G-YPZRK2Y3R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCDj_W54-r3sXvqx86a01I1OrGTMIvc1Q',
    appId: '1:482543933000:android:2b5d47b8fdd615c9c2aa7d',
    messagingSenderId: '482543933000',
    projectId: 'animagie-8f2fe',
    storageBucket: 'animagie-8f2fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGgsF1TEggBrY94wr-jFF1Ac2jliT_mcg',
    appId: '1:482543933000:ios:982a2ba926dae47ec2aa7d',
    messagingSenderId: '482543933000',
    projectId: 'animagie-8f2fe',
    storageBucket: 'animagie-8f2fe.appspot.com',
    iosClientId: '482543933000-ouuedbfdni4rdju184njjo2omfucta77.apps.googleusercontent.com',
    iosBundleId: 'com.animagie.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGgsF1TEggBrY94wr-jFF1Ac2jliT_mcg',
    appId: '1:482543933000:ios:864c1fd2fdb9779cc2aa7d',
    messagingSenderId: '482543933000',
    projectId: 'animagie-8f2fe',
    storageBucket: 'animagie-8f2fe.appspot.com',
    iosClientId: '482543933000-uc3r9h94jqsdi80de1s7967330k0f8lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.animagieeui',
  );
}
